required = [ "k8s.io/code-generator/cmd/client-gen", "k8s.io/gengo/types" ]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "k8s.io/gengo"
  non-go = false
  unused-packages = false

[[constraint]]
  name = "github.com/google/uuid"
  revision = "8c31c18f31ede9fc8eae72290a7e7a8064e9b3e3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.16.0"

[[constraint]]
  name = "k8s.io/utils"
  revision = "581e00157fb1a0435d4fac54a52d1ca1e481d60e"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "26a664648505d962332bda642b27306bc10d1082"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "master"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "master"
