// Package risk implements conditional update risk detection from a
// generic source.  For example, risks could come from the update
// service's conditionalEdges.  Or from firing in-cluster alerts.  Or
// from other sources.  This package makes it easy to extend the
// cluster-version operator with additional risk-detection sources over
// time.
package risk

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/blang/semver/v4"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"

	configv1 "github.com/openshift/api/config/v1"
)

// validName enforces the non-empty CamelCase risk-naming convention.
var validName = regexp.MustCompile(`^[A-Z][A-Za-z0-9.-]*$`)

// Source represents a risk source, like the update service's
// conditionalEdges.  Or firing in-cluster alerts.  Or another source.
type Source interface {
	// Name returns the source's name, which can be prefixed to
	// the returned risk names to avoid collisions when aggregating
	// in a single map.
	Name() string

	// Risks returns the current set of risks the source is aware of.
	// Implementations are encouraged to make this an inexpensive call,
	// for example by caching expensive precursors, so the caller does
	// not have to worry about the load generated by frequent calls.
	// Arguments are a context to allow cancellation, and a slice of all
	// update versions (for sources that are reporting on current cluster
	// state, and want any detected risks to apply to all versions).
	// Returns a slice of detected risks, and a map from each risk name
	// to the version strings that risk is associated with.
	Risks(ctx context.Context, versions []string) ([]configv1.ConditionalUpdateRisk, map[string][]string, error)
}

// Merge updates the input updates and conditionalUpdates by merging
// additional risks.  The versions map has risk names as the key, and
// a slice of version strings that risk should be merged into as the
// value.  It returns the modified updates and conditionalUpdates slices.
func Merge(updates []configv1.Release, conditionalUpdates []configv1.ConditionalUpdate, risks []configv1.ConditionalUpdateRisk, versions map[string][]string) ([]configv1.Release, []configv1.ConditionalUpdate, error) {
	var errs []error
	riskMap := make(map[string]configv1.ConditionalUpdateRisk, len(risks))
	invalidRiskMap := make(map[string]struct{}, len(risks))
	for _, risk := range risks {
		if !validName.MatchString(risk.Name) {
			invalidRiskMap[risk.Name] = struct{}{}
			errs = append(errs, fmt.Errorf("invalid risk name %q does not match %q", risk.Name, validName))
			continue
		}

		existingRisk, ok := riskMap[risk.Name]
		if ok {
			if diff := cmp.Diff(existingRisk, risk, cmpopts.IgnoreFields(configv1.ConditionalUpdateRisk{}, "Conditions")); diff != "" {
				errs = append(errs, fmt.Errorf("divergent definitions of risk %q from the merging source:\n%s", risk.Name, diff))
			}
			continue
		}
		riskMap[risk.Name] = risk
	}

	riskMissMap := make(map[string]struct{}, len(versions))
	versionRiskNames := make([]string, 0, len(versions))
	for riskName := range versions {
		if _, ok := invalidRiskMap[riskName]; ok {
			continue // we're already complaining about these
		}
		versionRiskNames = append(versionRiskNames, riskName)
	}
	sort.Strings(versionRiskNames)
	for _, riskName := range versionRiskNames {
		risk, ok := riskMap[riskName]
		if !ok {
			riskMissMap[riskName] = struct{}{}
			continue
		}
		for _, version := range versions[riskName] {
			found := false
			for i, update := range updates {
				if update.Version != version {
					continue
				}
				found = true
				conditionalUpdates = append(conditionalUpdates, configv1.ConditionalUpdate{
					Release: update,
					Risks:   []configv1.ConditionalUpdateRisk{risk},
				})
				updates = append(updates[:i], updates[i+1:]...)
				if len(updates) == 0 {
					updates = nil
				}
				break
			}
			if found {
				continue
			}
			for i, conditionalUpdate := range conditionalUpdates {
				if conditionalUpdate.Release.Version != version {
					continue
				}
				found = true
				riskFound := false
				for _, existingRisk := range conditionalUpdate.Risks {
					if existingRisk.Name != risk.Name {
						continue
					}
					riskFound = true
					if diff := cmp.Diff(existingRisk, risk, cmpopts.IgnoreFields(configv1.ConditionalUpdateRisk{}, "Conditions")); diff != "" {
						errs = append(errs, fmt.Errorf("divergent definitions of risk %q:\n%s", risk.Name, diff))
						continue
					}
					break
				}
				if !riskFound {
					conditionalUpdates[i].Risks = append(conditionalUpdate.Risks, risk)
				}
			}
			if !found {
				errs = append(errs, fmt.Errorf("cannot merge risk %q into unknown release version %q", risk.Name, version))
			}
		}
	}
	if len(riskMissMap) > 0 {
		riskMisses := make([]string, 0, len(riskMissMap))
		for riskName := range riskMissMap {
			riskMisses = append(riskMisses, riskName)
		}
		sort.Strings(riskMisses)
		errs = append(errs, fmt.Errorf("merge versions referenced unknown risks: %s", strings.Join(riskMisses, ", ")))
	}

	slices.SortFunc(conditionalUpdates, func(a, b configv1.ConditionalUpdate) int {
		va, errA := semver.Parse(a.Release.Version)
		vb, errB := semver.Parse(b.Release.Version)
		if errA == nil && errB == nil {
			return va.Compare(vb)
		} else if errA == nil {
			return 1
		} else if errB == nil {
			return -1
		}
		return strings.Compare(a.Release.Version, b.Release.Version)
	})

	for i := range conditionalUpdates {
		slices.SortFunc(conditionalUpdates[i].Risks, func(a, b configv1.ConditionalUpdateRisk) int {
			return strings.Compare(a.Name, b.Name)
		})
	}

	return updates, conditionalUpdates, errors.Join(errs...)
}
