apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-update-console-plugin
  namespace: openshift-cluster-update-console-plugin
  annotations:
    kubernetes.io/description: Nginx configuration for the cluster-update console plugin.
data:
  nginx.conf: |
    error_log /dev/stderr;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;
      server {
        listen              9001 ssl;
        listen              [::]:9001 ssl;
        ssl_certificate     /var/cert/tls.crt;
        ssl_certificate_key /var/cert/tls.key;
        root                /usr/share/nginx/html;
      }
    }
