apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: cluster-update-console-plugin
  annotations:
    kubernetes.io/description: The OpenShift cluster-update console plugin provides a web-console interface for managing ClusterVersion updates.
spec:
  displayName: Cluster Updates
  i18n:
    loadType: Preload
  backend:
    type: Service
    service:
      name: cluster-update-console-plugin
      namespace: openshift-cluster-update-console-plugin
      port: 9001
      basePath: /
