apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-update-console-plugin
  annotations:
    kubernetes.io/description: The OpenShift cluster-update console plugin provides a web-console interface for managing ClusterVersion updates.
    workload.openshift.io/allowed: management
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
