apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-version-operator
  namespace: openshift-cluster-version
  annotations:
    kubernetes.io/description: Dedicated Service Account for the Cluster Version Operator.
    include.release.openshift.io/self-managed-high-availability: "true"
