apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-status-controller
  annotations:
    kubernetes.io/description: Role that allows the update status controller to manage OpenShift UpdateStatus API
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
- apiGroups:
  - config.openshift.io/v1alpha1
  resources:
  - updatestatuses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: update-status-controller-updatestatus-admin
  annotations:
    kubernetes.io/description: Grant the update status controller permission to manage OpenShift UpdateStatus API
    include.release.openshift.io/self-managed-high-availability: "true"
subjects:
- kind: ServiceAccount
  name: update-status-controller
  namespace: openshift-cluster-version
roleRef:
  kind: ClusterRole
  name: update-status-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: update-status-controller-cluster-reader
  annotations:
    kubernetes.io/description: Grant the update status controller permission to read cluster resources (temporary, until we have UpdateInformer producers)
    include.release.openshift.io/self-managed-high-availability: "true"
subjects:
- kind: ServiceAccount
  name: update-status-controller
  namespace: openshift-cluster-version
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
