apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-version
  annotations:
    openshift.io/node-selector: ""
  labels:
    name: openshift-cluster-version
    openshift.io/run-level: "1"
    openshift.io/cluster-monitoring: "true"
