apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-payload
  namespace: openshift-cluster-version
  annotations:
    kubernetes.io/description: Dedicated Service Account for the Update Payload.
    include.release.openshift.io/self-managed-high-availability: "true"
