apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-update-console-plugin
  namespace: openshift-cluster-update-console-plugin
  annotations:
    kubernetes.io/description: The OpenShift cluster-update console plugin provides a web-console interface for managing ClusterVersion updates.
    capability.openshift.io/name: Console
    release.openshift.io/feature-set: TechPreviewNoUpgrade
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  selector:
    matchLabels:
      app: cluster-update-console-plugin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        openshift.io/required-scc: restricted-v3
      labels:
        app: cluster-update-console-plugin
    spec:
      automountServiceAccountToken: false
      containers:
      - name: plugin
        image: placeholder.url.oc.will.replace.this.example.org:cluster-update-console-plugin
        imagePullPolicy: IfNotPresent
        ports:
        - name: https
          containerPort: 9001
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/cert
          name: cluster-update-console-plugin-cert
          readOnly: true
      dnsPolicy: Default
      hostUsers: false
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - name: cluster-update-console-plugin-cert
        secret:
          defaultMode: 420
          secretName: cluster-update-console-plugin-cert
