apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: etcd
  namespace: openshift-etcd
spec: {}
status:
  versions:
  - name: operator
    version: 0.0.1-snapshot
