apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: openshift-cluster-update-console-plugin
  annotations:
    kubernetes.io/description: The OpenShift cluster-update console plugin provides a web-console interface for managing ClusterVersion updates.
    capability.openshift.io/name: Console
    release.openshift.io/feature-set: TechPreviewNoUpgrade
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  displayName: Cluster Updates
  i18n:
    loadType: Preload
  backend:
    type: Service
    service:
      name: cluster-update-console-plugin
      namespace: openshift-cluster-update-console-plugin
      port: https
      basePath: /
