apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cvo-leader-election
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cvo-leader-election-binding
  namespace: openshift-cluster-version
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cvo-leader-election
subjects:
- kind: ServiceAccount
  name: cluster-version-operator
  namespace: openshift-cluster-version
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cvo-required-config-reader
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
- apiGroups: ["config.openshift.io"]
  resources: ["featuregates", "clusteroperators", "clusterversions", "proxies", "infrastructures"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cvo-configmap-reader
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cvo-config-configmap-binding
  namespace: openshift-config
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cvo-configmap-reader
subjects:
- kind: ServiceAccount
  name: cluster-version-operator
  namespace: openshift-cluster-version
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cvo-managed-configmap-binding
  namespace: openshift-config-managed
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cvo-configmap-reader
subjects:
- kind: ServiceAccount
  name: cluster-version-operator
  namespace: openshift-cluster-version
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cvo-required-config-binding
  annotations:
    kubernetes.io/description: Grant the cluster-version operator featuregate specific permissions.
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  kind: ClusterRole
  name: cvo-required-config-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-version
  name: cluster-version-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-version-operator
  annotations:
    kubernetes.io/description: Grant the cluster-version operator permission to perform cluster-admin actions while managing the OpenShift core.
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-version
  name: cluster-version-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-version-operator-scc-privileged-access
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
subjects:
- kind: ServiceAccount
  name: cluster-version-operator
  namespace: openshift-cluster-version
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-version-operator-payload-scc-privileged-access
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
subjects:
- kind: ServiceAccount
  name: update-payload-dedicated-sa
  namespace: openshift-cluster-version
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
