apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-update-console-plugin
  namespace: openshift-cluster-update-console-plugin
  annotations:
    kubernetes.io/description: The OpenShift cluster-update console plugin provides a web-console interface for managing ClusterVersion updates.
    capability.openshift.io/name: Console
    release.openshift.io/feature-set: TechPreviewNoUpgrade
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
