apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-status-controller
  namespace: openshift-cluster-version
  annotations:
    kubernetes.io/description: The update status controller manages OpenShift UpdateStatus API from insights collected from cluster components.
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: DevPreviewNoUpgrade
spec:
  selector:
    matchLabels:
      k8s-app: update-status-controller
  strategy:
    type: Recreate
  template:
    metadata:
      name: update-status-controller
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        k8s-app: update-status-controller
    spec:
      automountServiceAccountToken: false
      containers:
      - name: update-status-controller
        image: {{.ReleaseImage}}
        imagePullPolicy: IfNotPresent
        args:
        - "update-status-controller"
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: etc-ssl-certs
          readOnly: true
        - mountPath: /etc/tls/serving-cert
          name: serving-cert
          readOnly: true
        - mountPath: /etc/tls/service-ca
          name: service-ca
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access
          readOnly: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      serviceAccountName: update-status-controller
      terminationGracePeriodSeconds: 130
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists
        effect: "NoSchedule"
      - key: "node.kubernetes.io/network-unavailable"
        operator: Exists
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      volumes:
      - name: etc-ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: serving-cert
        secret:
          secretName: cluster-version-operator-serving-cert
      - name: service-ca
        configMap:
          name: openshift-service-ca.crt
      - name: kube-api-access
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3600
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
