apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvo-dedicated-sa
  namespace: openshift-cluster-version
  annotations:
    kubernetes.io/description: Dedicated Service Account for the Cluster Version Operator.
    include.release.openshift.io/self-managed-high-availability: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-payload-dedicated-sa
  namespace: openshift-cluster-version
  annotations:
    kubernetes.io/description: Dedicated Service Account for the Update Payload.
    include.release.openshift.io/self-managed-high-availability: "true"
