apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/description: Secret containing the kube-rbac-proxy configuration.
      It allows only HTTPS requests to the /metrics endpoint for the Prometheus
      service account.
    include.release.openshift.io/self-managed-high-availability: "true"
  name: openshift-cluster-version-kube-rbac-proxy-metric
  namespace: openshift-cluster-version
stringData:
  config.yaml: |-
    "authorization":
      "static":
      - "path": "/metrics"
        "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
        "verb": "get"
type: Opaque
