apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-gates
  namespace: openshift-config-managed
  annotations:
    kubernetes.io/description: Define update gates for the administrator to acknowledge in the admin-acks ConfigMap in the openshift-config namespace.
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
data:
  ack-4.18-kube-1.32-api-removals-in-4.19: |-
    Kubernetes 1.32 and therefore OpenShift 4.19 remove several APIs which require admin consideration. Please see the knowledge article https://access.redhat.com/articles/7112216 for details and instructions.
  ack-4.18-admissionregistration-v1beta1-api-removals-in-4.20: |-
    The admissionregistration.k8s.io/v1beta1 group version is deprecated in 4.18 and will be removed in 4.20. The admissionregistration.k8s.io/v1 group version is available for use in 4.18, and resources must be migrated to it before upgrading to 4.20.
